hmLoadTopic({
hmKeywords:"",
hmTitle:"Data link capability",
hmDescription:"The HsM system can also manage pure analog dispensers (with no data link to the HsM Backend), this device filter term type can be used to filter devices by their capability to...",
hmPrevLink:"customer.html",
hmNextLink:"device-type.html",
hmParentLink:"device-filter-term-types.html",
hmBreadCrumbs:"<a href=\"backend-infrastructure.html\">Backend infrastructure<\/a> &gt; <a href=\"client-service.html\">Client Service<\/a> &gt; <a href=\"device-filter.html\">Device filter<\/a> &gt; <a href=\"device-filter-term-types.html\">Device filter term types<\/a>",
hmTitlePath:"Backend infrastructure > Client Service > Device filter > Device filter term types > Data link",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Data link capability<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">The HsM system can also manage pure analog dispensers (with no data link to the HsM Backend), this device filter term type can be used to filter devices by their capability to send data to the &lt;%BACKEND%.<\/p>\n\r<p class=\"p_Normal\">Note this term type will not filter for devices that actually send data to the HsM Backend but only filters for their theoretical ability to send data.<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Settings<\/span><\/h1>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"width:45.0000rem; border:none; border-spacing:0; border-collapse:collapse;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:11.2500rem; background-color:#DCDCDC; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Setting<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; background-color:#DCDCDC; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Description<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Data link capability<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Can send data: Filters for devices that can send data to the HsM Backend. <\/p>\n\r<p class=\"p_Normal\">Cannot send data: Filters for devices that cannot send data to the HsM Backend<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Include compound members<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">If a device is a compound device and has a compound member that can send data to the HsM Backend these devices will pass the filter if this option is set.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_ImageCaption\"><a id=\"fig_96ed33\" class=\"hmanchor\"><\/a><span class=\"f_ImageCaption\">Table 5: Settings of this device term type<\/span><\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Validity constraints<\/span><\/h1>\n\r<p class=\"p_Normal\">This term type has no validation rules.<\/p>\n\r"
})
