hmLoadTopic({
hmKeywords:"",
hmTitle:"Glossary",
hmDescription:"BLE Bluetooth Low Energy. Wireless personal area network technology. BLE-networked device HsM devices that send or receive data via BLE. BLE-networked devices rely on gateways t",
hmPrevLink:"eui-(extended-unique-identifie.html",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Glossary",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Glossary<\/span><\/h1>\n\r",
hmBody:"<div style=\"text-align: left; text-indent: 0; line-height: 1.44; padding: 0 0 0 0; margin: 0.3750rem 0 0.2500rem 0;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; width:10.9375rem; padding:0; border:none\"><p class=\"p_Normal\"><a id=\"ble\" class=\"hmanchor\"><\/a>BLE<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.8750rem; padding:0; border:none\"><p class=\"p_Normal\">Bluetooth Low Energy. Wireless personal area network technology.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:10.9375rem; padding:0; border:none\"><p class=\"p_Normal\"><a id=\"ble-networked-device\" class=\"hmanchor\"><\/a>BLE-networked device<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.8750rem; padding:0; border:none\"><p class=\"p_Normal\">HsM devices that send or receive data via BLE. BLE-networked devices rely on gateways that will forward the data to\/from the HsM HsM Backend via <\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:10.9375rem; padding:0; border:none\"><p class=\"p_Normal\"><a id=\"mobile-gateway\" class=\"hmanchor\"><\/a>mobile gateway<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.8750rem; padding:0; border:none\"><p class=\"p_Normal\">HsM Apps with the ability to act as gateways between BLE-networked devices and the HsM HsM Backend are called mobile gateways.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:10.9375rem; padding:0; border:none\"><p class=\"p_Normal\"><a id=\"stationary-gateway\" class=\"hmanchor\"><\/a>stationary gateway<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.8750rem; padding:0; border:none\"><p class=\"p_Normal\">Hardware devices that connect BLE-networked devices to the HsM HsM Backend.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:10.9375rem; padding:0; border:none\"><p class=\"p_Normal\"><a id=\"gateway\" class=\"hmanchor\"><\/a>gateway<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.8750rem; padding:0; border:none\"><p class=\"p_Normal\">HsM devices that act as gateway between BLE-networked devices and the HsM HsM Backend. Can be mobile gateways or stationary gateways.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
