hmLoadTopic({
hmKeywords:"",
hmTitle:"Version 3",
hmDescription:"Version 3 of HsM serial numbers are fixed length serial numbers (13 characters). The serial number is case insensitive.",
hmPrevLink:"v2.html",
hmNextLink:"decision.html",
hmParentLink:"serial-numbers.html",
hmBreadCrumbs:"<a href=\"comm.html\">Common<\/a> &gt; <a href=\"serial-numbers.html\">Serial Numbers<\/a>",
hmTitlePath:"Common > Serial Numbers > Version 3",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Version 3<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Version 3 of HsM serial numbers are fixed length serial numbers (13 characters). The serial number is case insensitive.<\/p>\n\r<p class=\"p_Normal\">Regex: <span class=\"f_InlineCode\">([1-3][0-9])([01][0-9])([0123][0-9])([A-Za-z0-9]{3})([A-Za-z0-9]{4})<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"width:45.0000rem; border:none; border-spacing:0; border-collapse:collapse;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:6.6250rem; background-color:#DCDCDC; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Characters<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; width:38.1250rem; background-color:#DCDCDC; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Content<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; width:6.6250rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">1 - 6<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:38.1250rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Production date: Date when the device this component was initially part of passed the end test. Not necessarily the same as the Birth Date recorded in the device\'s digital twin.<\/p>\n\r<p class=\"p_Normal\">Date is given in format <span class=\"f_InlineCode\">yyMMdd<\/span> and must represent a valid date. <\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:6.6250rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">7 - 9<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:38.1250rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Production line: Identifier of the production line that produced the device the component was initially part of. Formatted as base 36 cipher<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:6.6250rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">10 - 13<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:38.1250rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Sequential number defined during the end-test. Formatted as base 36 cipher<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Example<\/span><\/h1>\n\r<p class=\"p_Normal\">201218FH10102<\/p>\n\r<p class=\"p_Normal\">Production date: 201218 = 2020-12-18<\/p>\n\r<p class=\"p_Normal\">Production line: FH1<\/p>\n\r<p class=\"p_Normal\">Sequntial number: &nbsp;0102<\/p>\n\r"
})
