pageinfo = [[1613388795,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613375395,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388791,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613115698,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613115698,0,0,0,null],
	[1613388795,0,0,0,null],
	[1611559838,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613112693,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613375395,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613112693,0,0,0,null],
	[1613115702,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613112700,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388796,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613375395,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613112701,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613115698,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613375395,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613112701,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613112701,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613115698,0,0,0,null],
	[1612961533,0,0,0,null],
	[1613115698,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388792,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388797,0,0,0,null],
	[1613388795,0,0,0,null],
	[1611559838,0,0,0,null],
	[1613388798,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388793,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388798,0,0,0,null],
	[1613115698,0,0,0,null],
	[1613388787,0,0,0,null],
	[1613388798,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613388795,0,0,0,null],
	[1613388790,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388794,0,0,0,null],
	[1613388789,0,0,0,null],
	[1613388788,0,0,0,null],
	[1613388798,0,0,0,null],
	[1613388794,0,0,0,null]];
pagedata = [ ["./adaptive-date-interval-specifi.html","Adaptive date interval definition","Adaptive date intervals definitions are not statically defined date intervals but rather use offsets and other settings to provide a blueprint for...",""],
["./administrators-guide.html","Administrator&#39;s Guide","Installation Maintenance",""],
["./administrators-guide2.html","Administrator&#39;s Guide","Enter topic text here.",""],
["./administrators-guide_2.html","Administrator&#39;s Guide","Installation Maintenance",""],
["./article-numbers.html","Article numbers","Enter topic text here.",""],
["./authentication-and-authorizato.html","Authentication","The HsM Catalog Service Browse API allows anonymous access to all its endpoints. To get data from these browse endpoints the client however has to...",""],
["./authentication.html","Authentication","Users &#38; Organizations  ^ Usertypen B2C: User Management Tool DOrt weredn user verwaltet Dev un Integration eines, Stage und production ei...",""],
["./authorization.html","Authorization","The entities managed through the Catalog Service’s Admin API are protected using policies",""],
["./authorization2.html","Authorization","Permissions: Permissions sind die kleinsten Atome. Permissions sind vom System vordefiniert. Permission können sich auf bestimme Wirklungsbereich ...",""],
["./autzorization-and-uthenticatio.html","Authorization and Authentication","Enter topic text here.",""],
["./backend-infrastructure.html","Backend infrastructure","Enter topic text here.",""],
["./cat-resource-instance-equivalents.html","Resource instance equivalents","Resource instance equivalents are global catalog elements that are used to link resource instances with the same logical meaning across different ...",""],
["./catalog-element-description.html","Catalog Element Description","For many entities managed in the Catalog Service the Catalog Service stores descriptive information in form of catalog element descriptions. A cat...",""],
["./catalog-service.html","HsM Catalog Service","The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of HsM to dynamically adapt to new dev...",""],
["./cats-device-type.html","Device type","A device type is the scheme that defines the logical and physical structure of HsM device. This includes the components that are used for instance...",""],
["./client-service.html","Client Service","Enter topic text here.",""],
["./clse-devicefilter-compounddevicehandling.html","Handling of compound devices","If a devices that matches the filter has member devices or is a member device then the Parent or Children are also delivered in the result set.",""],
["./clse-devicefilter-executionscope.html","Execution Scope","When a device filter is executed, it is always executed in a specific scope. This execution scope defines the base set of devices to which the fil...",""],
["./clse-devicefilter-logicaloperators.html","Logical operators","Device filters support following logical operators:",""],
["./clse-devicefilter-scopeavailability.html","Scope Availability ","Help for the UI",""],
["./clse-devicefilter-termtypeavailability.html","Term type availability","Some device filter terms are restricted to HsM users with specific permissions.",""],
["./clse-devicefilter.html","Device filter","A device filter is a logical expression that can be applied to the devices managed by the HsM Client Service to filter for a subset of these devic...",""],
["./clse-devicefiltertermtype-birthdate.html","Birth date","Filters by birth date of the device (or to be exact by the birth date of the digital twin).",""],
["./clse-devicefiltertermtype-compounddevicestatus.html","Compound device status","Compound member devices are part of the base set of devices to which device filters are applied, i.e. in the base set of devices to which the devi...",""],
["./clse-devicefiltertermtype-customer.html","Customer","Filters for devices assigned to a given customer. Settings Setting Description Customer Only devices assigned to that customer will pass the filte...",""],
["./clse-devicefiltertermtype-devicetype.html","Device type","Filters for devices that are of one of the given device types.",""],
["./clse-devicefiltertermtype-installationdate.html","Installation date","Filters for devices based on their installation date, i.e. the date when the device was installed at a specific locaiton.",""],
["./clse-devicefiltertermtype-latestequivalentresourceinstancevalue.html","Latest equivalent resource instance value","Enter topic text here.",""],
["./clse-devicefiltertermtype-latestresourceinstanceupdate.html","Latest resource instance update","Filters for devices that sent a resource instance value (for any resource instance) within the configured time span.",""],
["./clse-devicefiltertermtype-latestresourceinstancevalue.html","Latest resource instance value","Filters devices by their latest reported resource instance values. ",""],
["./clse-devicefiltertermtype-location.html","Location","Filters for devices that are installed at specific locations with in the location tree of customers.",""],
["./clse-devicefiltertermtype-organization.html","Organization","Filters for devices assigned to customers within an given organization.",""],
["./clse-devicefiltertermtypes.html","Device filter term types","Device filter term types are predefined building blocks for device filters. Term types can have settings and have their own validation rules.",""],
["./clse.html","Client Service","Enter topic text here.",""],
["./combining-devices.html","Combining devices","Compound devices can either be created by the Digital Twin registration agent when the device is first registered, or they can be created through ...",""],
["./command-line-start.html","Running from command line","...exe --environemnt=dev",""],
["./comments_and_questions.html","Getting help","Please enable JavaScript to view this site. ",""],
["./common.html","Common","Enter topic text here.",""],
["./component-types.html","Component types","Component types are used in device types to specify which kind of components can be used to fill a component placeholder. Besides the basic type o...",""],
["./compound-device-status.html","Compound device status","Compound member devices are part of the base set of devices to which device filters are applied, i.e. in the base set of devices to which the devi...",""],
["./compound-device-types.html","Compound device types","nh  HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other devices, however, are mo...",""],
["./compound-devices.html","Compound devices","The Digital Twin Service supports compound device types. It records the current relationship between devices and keeps a history of relationships ...",""],
["./configuration-app.html","Configuration app","Enter topic text here.",""],
["./configuration-files.html","Configuration files","{ \"Logging\": { \"NLog\": { \"IncludeScopes\": false, \"ParseMessageTemplates\": true, \"CaptureMessageProper...",""],
["./configuration.html","Configuration","For running the Digital Twin Registration Agent a working directory and an environment name must be specified. The root working directory for all ...",""],
["./copyright_notice.html","Copyright notice","Copyright of this Reference Manual &#169; 2019-2021 &#60;%COMPANY%&#62;. All rights reserved. &#60;%PRODUCTLINE%&#62; is a registered trademark or trademar...",""],
["./customer-roles.html","Customer roles","Role XXX Assigned permission (with links to the permission topoic)",""],
["./customer.html","Customer","Filters for devices assigned to a given customer. Settings Setting Description Customer Only devices assigned to that customer will pass the filte...",""],
["./customers.html","Customer and Organizations","Kunden zusammenführen   Fall: Ein Kunde mit mehreren Lieferadressen Gemeinde Zell am See = Rechnungsempfänger Bauhof = Lieferkunde Lieferkund...",""],
["./data-analysis-service.html","Data Analysis Service","Enter topic text here.",""],
["./data-link-monitoring-protocol.html","Data link monitoring protocol","For reporting the status of non-gateway devices to the backend the stationary gateway shall use a simple protocol.",""],
["./data-link-monitoring-service-d.html","Data link monitoring service database","Data volume estimation Table: StationaryGatewayOnlineStatus 2E4 stationary gateways 100 bytes / record (rough estimation including page headers, i...",""],
["./data-link-monitoring-service-l.html","Data link monitoring service logic","The data link monitoring service records the result of monitoring data links between non-gateway devices and stationary gateways and the results o...",""],
["./data-link-monitoring-service.html","Data Link Monitoring Service","HsM stationary gateways are used to connect non-gateway devices to the HsM Backend permanently and therefore enable a near-real-time uplink commun...",""],
["./data-link.html","Data link","The HsM system can also manage pure analog dispensers (with no data link to the HsM Backend), this device filter term type can be used to filter d...",""],
["./date-interval-definition.html","Date interval definitions","Date intervals are used to filter or query timestamped data that is within an given start date and end date. Since HsM deals with time-series a lo...",""],
["./date-interval.html","Date interval specification","Date intervals are used to filter or query timestamped data that is within an given start date and end date. Since HsM deals with time-series a lo...",""],
["./decision.html","Detect version of a &#60;%SYSTEMNAME%&#62; serial number","If length is exactly 13",""],
["./definitions.html","Definitions","device type: component type compound device type compound component",""],
["./delivering-device-types-via-th.html","Delivering device types via the browse API","When device types are requested and then delivered via the browse API their component type placeholders are resolved to component types, the accor...",""],
["./device-dates.html","Installation date","Filters for devices based on their installation date, i.e. the date when the device was installed at a specific locaiton.",""],
["./device-dates_2.html","Birth date","Filters by birth date of the device (or to be exact by the birth date of the digital twin).",""],
["./device-filter-term-types.html","Device filter term types","Device filter term types are predefined building blocks for device filters. Term types can have settings and have their own validation rules.",""],
["./device-filter.html","Device filter","A device filter is a logical expression that can be applied to the devices managed by the HsM Client Service to filter for a subset of these devic...",""],
["./device-provisioning-registrati.html","Device Provisioning Registration Agent","Flow:  * Start process every X hours at timestamp t * Get all stationary gateway devices from Provider DB, born after t - X - delta   De...",""],
["./device-provisioning-service.html","Device Provisioning Service","HsM uses an Azure Device Provisioning service for Stationary gateways so that these gateways will initially connect to the right HsM OeM Partner&#39;s...",""],
["./device-qr-codes.html","HsMDevice QR Codes","All devices managed by the HsM have stickers with a QR code that carries information about the device. This QR code sticker can be used by clients...",""],
["./device-type.html","Device type","Filters for devices that are of one of the given device types.",""],
["./device-type2.html","Device type","A device type is the scheme that defines the logical and physical structure of HsM device. This includes the components that are used for instance...",""],
["./digital-birth.html","On Premise infrastructure","Enter topic text here.",""],
["./digital-twin-lifecycle-status.html","Digital Twin lifecycle","In HsM every digital twin has a defined life cycle state at all times. The Digital Twin Service keeps track of the life cycle state of devices and...",""],
["./digital-twin-registration-agen.html","Digital Twin Registration Agent","Enter topic text here.",""],
["./digital-twin-service.html","Digital Twin Service","The HsM Digital Twin Service is part of the 12:33 PM neutral backend. It is the place where digital twins for each produced HsM device are initial...",""],
["./disclaimer.html","Disclaimer","Due to continued product development, information in this Reference Manual can change without notice.  ",""],
["./display-groups.html","Display Groups","The display groups defined with a firmware variant version are a partition of the set of resource instances defined with that firmware variant ver...",""],
["./display-groups2.html","Resource instance compositions","While display groups defined with a firmware variant version give clients a hint how to visualize the set of resource instances within that firmwa...",""],
["./dtra-installation.html","Installation","Prerequisites .NET Core 3.1 runtime: The Digital Twin Registration Agent is a .NET Core 3.1.10 application and therefore the .NET Core 3.1 run tim...",""],
["./dtra-operations-guide.html","Operations guide","The Digital Twin Registration Agent is a Windows program that is intended to be run as a Windows Service but can (for debugging and testing purpos...",""],
["./dtra-queuing.html","Queuing","Enter topic text here.",""],
["./dtra.html","Digital Twin Registration Agent","Enter topic text here.",""],
["./enumerating-resource-instances.html","Enumerating resource instances","Since compound device types can contain multiple compound member device types, they can also contain multiple firmware types. Therefore the possib...",""],
["./environment-setting.html","Environment setting","Please enable JavaScript to view this site. ",""],
["./environment-variable-dtra_conf.html","Environment variable DTRA_CONFIG_DIR","The Windows System Environment Variable DTRA_CONFIG_DIR defines the directory where configuration files are expected and where the Digital Twin Re...",""],
["./example_topic.html","%Text%","Each topic begins with a short introduction or abstract that describes the contents of the topics. This topic is an example topic that shows all s...",""],
["./execution-scope.html","Execution Scope","When a device filter is executed, it is always executed in a specific scope. This execution scope defines the base set of devices to which the fil...",""],
["./extended-properties.html","Extended Properties","The Catalog Service can define extended properties for each device type. The Digital Twin Service is the place where the values for these extended...",""],
["./extended-properties2.html","Extended Properties","Each device type can have definitions for extended properties. Extended properties are properties of devices that are instances extended property ...",""],
["./frontends.html","Frontends","Enter topic text here.",""],
["./gateway-devices.html","Gateway devices","In HsM gateways are also handled as HsM devices and have their own data-link status.",""],
["./global-roles.html","Global roles","Enter topic text here.",""],
["./handling-of-compound-devices.html","Handling of compound devices","If a devices that matches the filter has member devices or is a member device then the Parent or Children are also delivered in the result set.",""],
["./handling-of-invalid-device-filters.html","Validity constraints","Several constraints must be fulfilled for a device filter to be called valid. This includes constraints that apply to the structure of the express...",""],
["./hsm-oem-customers.html","HsM OEM Customers","Entities in the Catalog Service are mapped to one or more OEM Customers. E.g. a device type is mapped to one or more OEM-Customers.",""],
["./index.html","Preface","Enter topic text here.",""],
["./installation.html","Installation","Prerequisites .NET Core 3.1 runtime: The Digital Twin Registration Agent is a .NET Core 3.1.10 application and therefore the .NET Core 3.1 run tim...",""],
["./intended_audience.html","Intended audience","This Reference Manual covers all aspects of HsM. It includes information for the occasional system user, power users, administrators but also for ...",""],
["./introduction.html","Introduction","Please enable JavaScript to view this site. ",""],
["./introduction2.html","Introduction","HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other devices, however, are more than j...",""],
["./latest-status-update.html","Latest status update","Filters for devices that sent a resource instance value (for any resource instance) within the configured time span.",""],
["./life-cycle-status.html","Life cycle status","Enter topic text here.",""],
["./lifecycle-state.html","Lifecycle state","The lifecycle state represents the actual lifecycle state of a catalog element. It can be used to restrict access of elements to a certain group o...",""],
["./location-of-configuration-file.html","Location of configuration file","All  configuration for Digital Twin Registration Agent is done through a configuration file. ",""],
["./location-tree-filter.html","Location tree filter","Filters for devices that are installed at specific locations with in the location tree of customers.",""],
["./locking.html","Locking","For some operations on customer data in HSM the customer needs to be locked, so that no data inconsistencies can occur. This is mostly caused by t...",""],
["./logging.html","Logging","For monitoring the Digital Twin Registration Agent the program logs via the nlog framework and therefore allows for versatile routing of log messa...",""],
["./logging2.html","Logging","Enter topic text here.",""],
["./logical-operators.html","Logical operators","Device filters support following logical operators:",""],
["./monitoring-data-link-between-n.html","Monitoring data link between non-gateway devices and stationary gateways","Gateways actively monitor the Bluetooth communication links with non-gateway devices and report the status of this links to the Data link monitori...",""],
["./monitoring-data-link-between-s.html","Monitoring data link between stationary gateways and the HsM backend","The Data link monitoring service monitors the data link between stationary gateways and the HsM Backend. The technical environment allows to immed...",""],
["./neutral-backend-infrastructure.html","Neutral backend infrastructure","HsM is designed to be operated by different HsM OEM Partners, I.e. different OEM Partner can host their own HsM infrastructure and can therefore o...",""],
["./non-gateway-devices.html","Non gateway devices","The data-link between a non-gateway device and the HsM Backend via gateways can be in one of the following states:",""],
["./operations-guide.html","Operations Guide","Enter topic text here.",""],
["./operations-guide2.html","Operations guide","Enter topic text here.",""],
["./operations-guide3.html","Operations guide","Enter topic text here.",""],
["./operations-guide4.html","Operations guide","The Digital Twin Registration Agent is a Windows program that is intended to be run as a Windows Service but can (for debugging and testing purpos...",""],
["./organization-roles.html","Organization roles","Enter topic text here.",""],
["./organization.html","Organization","Filters for devices assigned to customers within an given organization.",""],
["./permissions.html","Permissions","Code Description Scope Applicability VIEW_CUSTOMER   VIEW_CUSTOMER_DETAILS   VIEW_DEVICES   EDIT_DEVICES   EDIT_LOCATIONS &#38;nbs...",""],
["./placeholder-visibility.html","Placeholder visibility","Component placeholders are marked with an visibility attribute. This attribute is a hint to software products showing either the device type&#39;s com...",""],
["./predefined-adaptive-date-inter.html","Predefined adaptive date intervals","For easier definition of adaptive date intervals the HsM Client Service provides some predefined date intervals",""],
["./presented-data-link-status.html","Data link status","Please enable JavaScript to view this site. ",""],
["./primary-data-processing.html","Primary Data Processing","HsM uses Azure IoT Hub infrastructure for device-to-cloud and cloud-to-device communication.",""],
["./problem-types.html","Problem types","Enter topic text here.",""],
["./provieder-db.html","Provider DB","When inserting a record with ProductRecordStateId = 0 the TRG_TRACE_Product_InsteadOfInsert trigger will intercept the insert and will apply follo...",""],
["./queue.html","Queue","The queue subdirectory is used as a queue for devices that need to be registered with the Digital Twin Service. The queue directory is filled by q...",""],
["./queuing.html","Queuing","Enter topic text here.",""],
["./recording-of-data-link-status.html","Recording of data link status","The data link status of HsM Backend devices (non-gateway as well as gateway devices) is recorded as virtual resource instance values for each devi...",""],
["./removing-a-windows-service.html","Removing a Windows Service","Using PowerShell Note you need to run PowerShell with administrative privileges to modify Windows Services. Removing a Windows Service for the Dig...",""],
["./resource-equivalent-latest-val.html","Resource equivalent latest value","Enter topic text here.",""],
["./resource-instance-equivalents.html","Resource instance equivalents","Resource instance equivalents are global catalog elements that are used to link resource instances with the same meaning accross different  d...",""],
["./resource-instance-value2.html","Latest Resource instance value","Filters devices by their latest reported resource instance values. ",""],
["./rest-api.html","REST API","The REST API documentation of the HsM Catalog Service can be found at http://catalog.hsm.digital/swagger/index.html.",""],
["./roles.html","Roles","Enter topic text here.",""],
["./run-as-windows-service.html","Creating a Windows Service","While there are many ways to register a program as a Windows Service, we recommend the following approach with PowerShell. Note you need to run Po...",""],
["./scope-availability-.html","Scope Availability ","Help for the UI",""],
["./serial-numbers.html","Serial Numbers","Serial numbers are used to uniquely identify components of HsM devices. A device can be uniquely identified by the serial number of one of its com...",""],
["./service-app.html","Service App","Enter topic text here.",""],
["./starting-and-stopping-the-wind.html","Running as Windows service","Enter topic text here.",""],
["./static-date-interval-definition.html","Static date interval definition","A static date interval definitions are specified by a fixed lower boundary and upper boundary.",""],
["./static-date-interval-specifica.html","Static date interval specification","A static date interval specification contain a fixed lower and upper boundary.",""],
["./status_of_topics.html","Status of topics","We use the status of the topics to define the working status and the releas status",""],
["./support.html","Support","Please enable JavaScript to view this site. ",""],
["./technical-check.html","Technical Check","Definition of overdue The technical checks for a customer has a due date d The technical check for a customer has a grace period before g1, and gr...",""],
["./term-type-availability.html","Term type availability","Some device filter terms are restricted to HsM users with specific permissions.",""],
["./time-series-storage.html","Time Series Storage","Enter topic text here.",""],
["./time-synchronization.html","Time synchronization","The Digital Twin Registration Agent uses an incremental approach when registering devices. I.e. it checks for changes in the provider DB regularly...",""],
["./transmission-mode.html","Latest transmission mode","Devices can transmit value on occasion (typical for mobile gateways) or as result of a trigger event like a dispense action (typical for devices c...",""],
["./typographic_conventions.html","Typographic conventions","The following typographic conventions are used in this Reference Manual.",""],
["./updating.html","Updating","Updating the Digital Twin Registration Agent is done by replacing all the files int he program directory with the files of the new version - just ...",""],
["./v1.html","Version 1","Lentgh: variable 1 - 6: Date yyMMdd 7 - 9 Line (base 36 cipher) 10 - 13: Sequential Number (base 36 cipher)",""],
["./v2.html","Version 2","Product Type coe  2005-200916-00202",""],
["./v3.html","Version 3","Version 3 of HsM serial numbers are fixed length serial numbers (13 characters). The serial number is case insensitive.",""],
["./validating-device-filters.html","Validating device filters","The HsM Client Service provides the possibility to validate a device filter and report the result so this validation in a human readable way. This...",""],
["./visibility.html","Visibility","Some information managed in the Catalog Service is marked with a visibility attribute. This visibility attribute is a hint to other systems using ...",""],
["./web-portal.html","Web portal","Enter topic text here.",""],
["./wizards.html","Wizards","A wizard in HSM is a user interface that presents a user with a sequence of views that leads the user through a series of steps. In HSM wizards ar...",""],
["./wording.html","Wording","Wording in Catalog: Compound device type: Device type with at least one device type placeholder. Compound member device type: Device type that can...",""],
["./working-directory.html","Working directory","The DTRA will create a working directory within the configured  DTRA_CONFIG_DIR the name of the working directory will be data.&#60;environmen...",""],
["./xibu-app.html","Xibu App","Enter topic text here.",""]];
